# Prometheus Configuration for QNTI Trading System
# Monitoring and alerting configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'qnti-trading-system'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load alerting rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # QNTI Application metrics
  - job_name: 'qnti-app'
    static_configs:
      - targets: ['qnti-app:5000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    basic_auth:
      username: 'monitoring'
      password: 'monitoring_password'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node/System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Custom QNTI business metrics
  - job_name: 'qnti-business-metrics'
    static_configs:
      - targets: ['qnti-app:5000']
    scrape_interval: 30s
    metrics_path: '/metrics/business'
    params:
      format: ['prometheus']
    basic_auth:
      username: 'monitoring'
      password: 'monitoring_password'

  # Trading performance metrics
  - job_name: 'qnti-trading-metrics'
    static_configs:
      - targets: ['qnti-app:5000']
    scrape_interval: 60s
    metrics_path: '/metrics/trading'
    params:
      format: ['prometheus']
    basic_auth:
      username: 'monitoring'
      password: 'monitoring_password'

  # Health check endpoints
  - job_name: 'qnti-health'
    static_configs:
      - targets: ['qnti-app:5000']
    scrape_interval: 10s
    metrics_path: '/health'
    params:
      format: ['prometheus']

# Remote write configuration (for external monitoring)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"

# Remote read configuration (for external monitoring)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"